development:
  adapter: postgresql
  encoding: unicode
  database: rormetrics_development
  pool: 5
  username: spatel
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rormetrics_test
  pool: 5
  username: spatel
  password: